### ISSUE TITLE
CGYRO doesn't actually use conventional Miller

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#143]
@d7919 @mgiacomin @dake0795 @hgd511 

I have just realised that CGYRO doesn't actually use conventional Miller geometry at all. 
i.e this is **not** the parameterisation
![image](https://user-images.githubusercontent.com/15210802/206260908-7ed168a8-c59a-4cd1-beb0-43d31164dbd0.png)

It **only** uses Miller extended harmonic, so the squareness `zeta` in CGYRO (below s2) is not the same as the squareness `zeta` in GENE (above).
![image](https://user-images.githubusercontent.com/15210802/206261006-9a1468cf-baa0-426f-9a31-ed75c22a5c83.png)

They happen to be the same squareness (in either code) is set to 0 and only the triangularity is included, but otherwise they are different and can't be compared.

Having only recently added squareness this is not a huge deal but we need to think how to handle this going ahead as Miller now means two things. This may requires having `MillerCGYRO` and `MillerGENE`

I have double checked both codes and they are definitely different when defining `R` and `Z

**Comment by mgiacomin** [comment]
If I understand correctly, the Miller parametrisation is identical with squareness set to zero. Adding a squareness different from zero would require to treat CGYRO and GENE geometries differently, which adds another degree of complexity. I am just wondering of how much a fit can be improved by adding the squareness and if it is worth adding this extra degree of complexity just to treat the different definition of `zeta`.

**Comment by bpatel2107** [comment]
The issue lies when there is an existing CGYRO/GENE file that has `zeta` already defined. If we're not careful then when converting we won't have a good cross-code comparison as the physical flux surfaces will be different. 

Also MAST-U plasmas have been quite square which has potentially impacted the pedestal stability so I think from a physics perspective it is important to capture this. 

I think we can potentially handle this under the hood by making `MillerCGYRO` and `MillerGENE` inherit from a general `Miller` object so when the user sets the code to `Miller` pyro will calculate the coefficients for you when writing the code. (could also add in a `MillerGS2` that doesn't have squareness). It's not ideal but there's not much we can do without significantly changing the GK codes themselves.

**Comment by LiamPattinson** [comment]
[Link to the CGYRO geometry page, for reference.](https://gafusion.github.io/doc/geometry.html) It looks like $\zeta$ maps directly to $s_2$ in the equation above.

Just to make sure I'm following, is the issue here that the equation for CGYRO has squareness as a parameter of $R(r, \theta)$, while for GENE it's a parameter of $Z(r, \theta)$? It looks like they would be compatible if the equation for $Z(r, \theta)$ used $\theta_R$ instead of plain $\theta$ in the sine term.

If that is the case, could we therefore make an argument for introducing a super-Miller class that has harmonic terms for $\theta_R$ and $\theta_Z$?

```math
\displaylines{
R(r, \theta) = R_0(r) + r \cos(\theta_R)\\
Z(r, \theta) = Z_0(r) + \kappa(r)  r  \sin(\theta_Z)\\
\theta_R = \theta + c_{R0}(r) + \sum_{n=1}^{N_R} (c_{Rn}(r)  \cos(n \theta) + s_{Rn}(r) \sin(n \theta))\\
\theta_Z = \theta + c_{Z0}(r) + \sum_{n=1}^{N_Z} (c_{Zn}(r)  \cos(n  \theta) + s_{Zn}(r) \sin(n \theta))
}
```

I'm not sure how well this would work in practice, as having both $\theta_R$ and $\theta_Z$ might just over-determine the problem and lead to weird fitting issues. However, it would mean that you could implement just one Miller class, and subclasses could essentially just implement a new `__init__` function that forces the unwanted parameters to zero (although you'd also need some mechanism to inform the super class that those parameters should always remain zero, which could be tricky).

(Today I learned that Github markdown allows for maths. Neat.)

**Comment by ZedThree** [comment]
My suggestion would be to handle this the same way we handle normalisations and naming (at least philosophically): when we read in the equilibrium from a GK file, we convert it to our internal form; and when we write out a GK file, we convert to the code-specific form.

A potential downside is that converting back and forth from our internal Miller representation to a code-specific one might not be the identity, so reading and writing a GK file might suffer from that too.

**Comment by bpatel2107** [comment]
(Today I also learned that Github markdown allows for maths. Also neat.)

Something like what @LiamPattinson suggested could in theory work but each version would still requires an independent fit with different constraints. 

I.e. for CGYRO "Miller"
```math
c_{Zn} = 0 
```
```math
s_{Zn} = 0
```
for all n 

Essentially if you switch `gk_codes` you would need to refit in any case.

I think I agree with @ZedThree. What we could do is calculate, `R`, `Z` and `b_poloidal` for a given input file and whenever we fit we call the appropriate fitting routine for that code, having a `Miller` and `Fourier` option for each `gk_code`. We're not a million miles away atm. 

An issue would arise when flipping back and forth between codes as the stored `R` and `Z` wouldn't quite be the same so the fits wouldn't be the same. Not sure if there is a way around that...
