### ISSUE TITLE
Pyrokinetics length-scale normalization 

### ISSUE THREAD

**Issue by arkabokshi** [bpatel2107/pyrokinetics#163]
In the process of adding `GKW` to the codebase, I have come across the issue that in the `GKW` Miller parameterization, the only way to normalize the lengths is by the major radius $R_0$.  This makes me wonder:

1. Why do we use the machine minor radius $a$  to normalize lengths?

2. Would it perhaps be better to use $R_0$ instead since it would be more aligned with the [IMAS convention](https://gitlab.com/gkdb/gkdb/-/blob/master/doc/general/IOGKDB.pdf)? 

3. $a$ is never used anywhere in the simulations and can potentially introduce bugs. GENE for instance defines `minor_r` but this is never used.  So while a wrong value won't affect the GENE run, it is likely to affect the other inputs generated through Pyrokinetics.

4. Finally, there is no provision to define the minor radius in `GKW`.  So if we are sticking with the current convention, what would be a good way to proceed?

5. Do we also worry about the output and (check and) convert everything to $a/c_s$ ? (The $c_s  \rightarrow v_{th}$ mapping is indifferent to anything that goes into the input file, but not $a \rightarrow R_0$).

**Comment by bpatel2107** [comment]
We used the minor radius as CGYRO only uses the minor radius and this all started with just CGYRO and GS2 (how far we've come)

The issue mostly can be handled by the choice of normalisation we use, see here
https://github.com/pyro-kinetics/pyrokinetics/blob/153fb30f8034b50ef3d67662451b5a085296f056/pyrokinetics/normalisation.py#L236-L242

We do set `minor_r` in GENE but it might not do anything. The important thing there is to set `major_r` normalised to $L_{ref}$ which we can choose in pyro. Given that it isn't possible to get `minor_r` from GKW we will have to force the user to define `R_{maj}/a` for this scenario if we want to switch normalisations. I think we should be doing that for GENE now which may be an issue.

The output normalisation is not currently being handled well aren't being handled either so that is likely the next big re-factors. We do deal with the $\sqrt{2}$ manually in GS2 for example, but length scale and field are not correctly dealt with.

For now you can carry implement GKW whilst manually forcing the normalisations during the conversion. We will set up a more rigorous normalisation soon.

We are currently developing the tools to link to IMAS so all the re-normalisations will be added there.
