### ISSUE TITLE
Read moments in pyro

### ISSUE THREAD

**Issue by juanruizruiz** [bpatel2107/pyrokinetics#198]
I am implementing a synthetic diagnostic in pyro and would need pyro to read the moments of the distribution function (especially delta n). For CGYRO, the files are bin.cgyro.kxky_n, bin.cgyro.kxky_v, etc. This would be very useful! Thanks, Juan

**Comment by mgiacomin** [comment]
I see this has been started in the branch [https://github.com/pyro-kinetics/pyrokinetics/tree/enhancement/gk_output_moments](url). I am not sure if @bpatel2107 is still working on it. I think this requires some care since loading fields and moments together require a lot of memory. I have partially addressed this issue in GENE by introducing the variable `downsize`, which downsamples data while reading, but I think one would rather need to load a specific time interval (let's say the last _n_ time units) in order to reduce the memory requirements.

**Comment by bpatel2107** [comment]
I have started on this a little. We can likely take the code from there and dump it in the latest version of `GKOutputReader` without much work for CGYRO. I haven't looked at the other codes but I imagine it wouldn't be too different from loading the fields.

**Comment by bpatel2107** [comment]
Done in #182
