### ISSUE TITLE
Jetto impurity error handling can catch and then trigger the same error

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#204]
In the Jetto kinetics reader we try to construct impurity_charge and then impurity mass in a try, catch block. However the creation of impurity mass is identical in both cases so if the KeyError is in impurity mass this catches and then retriggers the same error.

https://github.com/pyro-kinetics/pyrokinetics/blob/408e25a20c4d12e8ca8233b3d772504dc404f16b/pyrokinetics/kinetics/KineticsReaderJETTO.py#L110-L130

This seems unexpected.

Note this was spotted as Arka was running with a case where the hard-coded `impurity_charge_to_mass` lookup doesn't have the impurity charge of interest. There's currently no way of extending the impurity charge -> mass mapping here without edits to the source code. I don't know if this is because JETTO only allows a finite set of impurities, but I would have thought that it could be helpful if the user could pass in extra charge->mass mappings to extend the hard-coded one.

Also am I correct in thinking the `impurity_charge.m` is short hand for `impurity_charge.magnitude` to get the value of charge dropping units?

**Comment by d7919** [comment]
This discrepancy is perhaps more apparent when considering heavy impurities where the mass is simply the mass number times the hydrogen mass. If this is fine why not just make the deuterium mass 2*hydrogen mass?

**Comment by bpatel2107** [comment]
This all arises from JETTO calculating the ionisation state for all species. What it actually spits out is a weighted average of all ionisation states which can lead to a non-integer value. Usually for lighter elements, the species will be fully ionised which is straightforward, but for heavier impurities this is not the case. What we really should be doing in finding the mass and setting the charge. The issue is I can't see the mass in the output. We could for the time being look at the value of charge in the core where any impurities are likely to be fully ionised though this isn't completely robust.

Note this means the charge actually should be a function of `psin` for impurities.

And yes `.m` is shorthand for `.magnitude`

In the except we use `rint` instead of `int` which rounds to the nearest integer. This was for cases where the charge would be close to the full ionisation state (1.999 for Helium instead of 2) but clearly isn't viable for heavy impurities
