### ISSUE TITLE
Minor inconsistency in ion mass treatment?

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#205]
https://github.com/pyro-kinetics/pyrokinetics/blob/408e25a20c4d12e8ca8233b3d772504dc404f16b/pyrokinetics/kinetics/KineticsReaderJETTO.py#L101

In the Jetto reader we use simple scalings of the hydrogen and deuterium mass to set the mass of tritium and alphas yet in constants we go out of our way to specify the deuterium density directly and not in terms of the hydrogen density.

https://github.com/pyro-kinetics/pyrokinetics/blob/408e25a20c4d12e8ca8233b3d772504dc404f16b/pyrokinetics/constants.py#L14

This is minor but seems an odd mix. Note also that the value of the deuterium density in constants doesn't seem to agree with the value from wolfram alpha, for example. As silly as it sounds, is it worth adding a reference for this?

**Comment by bpatel2107** [comment]
I agree that we should try and be more consistent here. Ideally we should use the mass of the ion directly rather than using the atomic number but I'm not sure where to find that in python

I used the value from here 
https://physics.nist.gov/cgi-bin/cuu/Value?md

But I think we can import this from `scipy.constants.physical_constants` which is the same as this.

If you search from deuteron mass (rather than deuterium mass) then is same to about 7 d.p.

**Comment by LiamPattinson** [comment]
The [mendeleev](https://pypi.org/project/mendeleev/) library might be useful here, maybe the [`Ion`](https://mendeleev.readthedocs.io/en/stable/notebooks/ions.html) class. [PlasmaPy](https://docs.plasmapy.org/en/stable/index.html) also has a [`Particle`](https://docs.plasmapy.org/en/stable/particles/index.html) class which might have this sort of info, but it uses AstroPy units which we'd either need to remove or convert to pint units.
