### ISSUE TITLE
JOSS paper review - Reviewer 1 

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#262]
The JOSS paper review has started and there are some issues that one of the reviewers has come across. Opening this issue to work through the issues faced by the first reviewer.

https://github.com/openjournals/joss-reviews/issues/5866#issuecomment-1766842546

**Comment by LiamPattinson** [comment]
- Not sure what's going on with the `pip install -e .[tests]` error. Maybe it's just not running on the latest pip? It may be worth adding `pip install --upgrade pip` throughout the README file.
- The failing tests are the same few that keep falling over in our CI. I think these golden answer tests may need to be replaced, as they seem far too sensitive to the user's system (or are they indicative that the Fourier geometry fitting actually isn't working?).
- The GS2 file that won't read seems to be because it's using features we don't (yet?) support. The error message reported is `KeyError: "'my_gs2.in' is neither a registered key nor a valid file."`, which isn't helpful. If you try running `p = Pyro(gk_file="my_gs2.in", gk_code="GS2")`, you get the much more helpful `NotImplementedError: GS2 equilibrium option file not implemented`. We should add some code to catch the generic KeyError that was raised, explain that the cause is an invalid input file, and recommend specifying `gk_code` to get a more useful error message. We can do the same for equilibrium and kinetics too. Unfortunately, I can't think of a way to get the correct error message without adding `gk_code`/`eq_type`/etc, as in the process of figuring out the file type, every invalid file reader raises their own exception, and there's no way to tell which of these exceptions are relevant.
- I can add a Dockerfile, and I can make it so that a new one is published automatically on each release. I don't have repository access rights to add workflow secrets though, so I'll have to coordinate that with somebody who does.

**Comment by ZedThree** [comment]
Personally, I think having a Docker container for pyrokinetics is little bit of overkill, and it would be much better to sort out any installation issues -- this will also make it easier to install in a container if we really need to go down that route. We might instead also check that the CLI works properly with `pipx`.

I do think it is probably a good idea to move most of the data files that we only need for the tests out to either another repo or something like zenodo.

Then it looks like the other issues are probably just making nicer error messages.

And then the other thing we might want to think about it is sorting out the dependencies, either making some optional, or doing lazy importing to make start up time much faster.

**Comment by bpatel2107** [comment]
@the-rccg please feel free to leave any comments you have here too

**Comment by bpatel2107** [comment]
I'd like to jump back to this. We've addressed all the major issues apart from the final issue from the first reviewer about the Docker file. I am leaning more towards it not being necessary but if it is easy to do then I'm not opposed to it. I'm not sure we have any more installation issues (barring the pygacode stuff)

To be honest I'm not really sure what a docker file does and from what I do know how it would benefit  pyro.
