### ISSUE TITLE
Auto-detect file types

### ISSUE THREAD

**Issue by ZedThree** [bpatel2107/pyrokinetics#32]
We can probably do this to some extent already with the kinetic files by looking for certain metadata, e.g. `TRANSP_version`. For GK input files, we could either look for unique namelists/variables if they're present, or perhaps metadata in comments. For example, GS2 now creates `<filename>.used_inputs.in` files after finishing a simulation, which contains a comment like `! GS2 version: 8.0.6-1858-g4d2e5ecb`.

It might not always be possible, but it would be neat.

**Comment by bpatel2107** [comment]
For the JETTO CDF this would also be possible as under the description is saved as a string `"JETTO profile data"`. 

For SCENE, the netCDF output doesn't have any metadata so we would need to add that into SCENE itself.

At the moment, when loading output data, you need to have the input file so we would need to have the autocheck on the input file which is possible but we'd need to be careful.

For CGYRO the output files are always written as `out.cgyro.*` so that is an easy check. It also write a `out.cgyro.version` file with the git has

GENE also writes out the git hash in the `parameter_000*` file

**Comment by ZedThree** [comment]
We could also write metadata to the files we write, which would allow us to identify them later if necessary

**Comment by bpatel2107** [comment]
Fixed in #58
